// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

package verifiabledatastructures

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Mutation struct {
	Namespace []byte `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// one of the following
	LogAddEntry *LogAddEntryRequest `protobuf:"bytes,2,opt,name=log_add_entry,json=logAddEntry" json:"log_add_entry,omitempty"`
}

func (m *Mutation) Reset()                    { *m = Mutation{} }
func (m *Mutation) String() string            { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()               {}
func (*Mutation) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Mutation) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Mutation) GetLogAddEntry() *LogAddEntryRequest {
	if m != nil {
		return m.LogAddEntry
	}
	return nil
}

type LeafNode struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *LeafNode) Reset()                    { *m = LeafNode{} }
func (m *LeafNode) String() string            { return proto.CompactTextString(m) }
func (*LeafNode) ProtoMessage()               {}
func (*LeafNode) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LeafNode) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type TreeNode struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *TreeNode) Reset()                    { *m = TreeNode{} }
func (m *TreeNode) String() string            { return proto.CompactTextString(m) }
func (*TreeNode) ProtoMessage()               {}
func (*TreeNode) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *TreeNode) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type LogTreeHash struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *LogTreeHash) Reset()                    { *m = LogTreeHash{} }
func (m *LogTreeHash) String() string            { return proto.CompactTextString(m) }
func (*LogTreeHash) ProtoMessage()               {}
func (*LogTreeHash) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *LogTreeHash) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type EntryIndex struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
}

func (m *EntryIndex) Reset()                    { *m = EntryIndex{} }
func (m *EntryIndex) String() string            { return proto.CompactTextString(m) }
func (*EntryIndex) ProtoMessage()               {}
func (*EntryIndex) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *EntryIndex) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ObjectSize struct {
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
}

func (m *ObjectSize) Reset()                    { *m = ObjectSize{} }
func (m *ObjectSize) String() string            { return proto.CompactTextString(m) }
func (*ObjectSize) ProtoMessage()               {}
func (*ObjectSize) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *ObjectSize) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type MapNode struct {
	// for parent nodes only
	LeftNumber  int64 `protobuf:"varint,1,opt,name=left_number,json=leftNumber" json:"left_number,omitempty"`
	RightNumber int64 `protobuf:"varint,2,opt,name=right_number,json=rightNumber" json:"right_number,omitempty"`
	// set for parents only, if corresponding entry is non-zero
	LeftHash  []byte `protobuf:"bytes,3,opt,name=left_hash,json=leftHash,proto3" json:"left_hash,omitempty"`
	RightHash []byte `protobuf:"bytes,4,opt,name=right_hash,json=rightHash,proto3" json:"right_hash,omitempty"`
	// for leaf nodes only
	LeafHash []byte `protobuf:"bytes,6,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Path     []byte `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
}

func (m *MapNode) Reset()                    { *m = MapNode{} }
func (m *MapNode) String() string            { return proto.CompactTextString(m) }
func (*MapNode) ProtoMessage()               {}
func (*MapNode) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *MapNode) GetLeftNumber() int64 {
	if m != nil {
		return m.LeftNumber
	}
	return 0
}

func (m *MapNode) GetRightNumber() int64 {
	if m != nil {
		return m.RightNumber
	}
	return 0
}

func (m *MapNode) GetLeftHash() []byte {
	if m != nil {
		return m.LeftHash
	}
	return nil
}

func (m *MapNode) GetRightHash() []byte {
	if m != nil {
		return m.RightHash
	}
	return nil
}

func (m *MapNode) GetLeafHash() []byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

func (m *MapNode) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func init() {
	proto.RegisterType((*Mutation)(nil), "com.continusec.verifiabledatastructures.storage.Mutation")
	proto.RegisterType((*LeafNode)(nil), "com.continusec.verifiabledatastructures.storage.LeafNode")
	proto.RegisterType((*TreeNode)(nil), "com.continusec.verifiabledatastructures.storage.TreeNode")
	proto.RegisterType((*LogTreeHash)(nil), "com.continusec.verifiabledatastructures.storage.LogTreeHash")
	proto.RegisterType((*EntryIndex)(nil), "com.continusec.verifiabledatastructures.storage.EntryIndex")
	proto.RegisterType((*ObjectSize)(nil), "com.continusec.verifiabledatastructures.storage.ObjectSize")
	proto.RegisterType((*MapNode)(nil), "com.continusec.verifiabledatastructures.storage.MapNode")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0x5b, 0xfb, 0xe7, 0xa4, 0x05, 0x19, 0x5c, 0x84, 0x5a, 0x69, 0xcd, 0xaa, 0xab,
	0x08, 0xfa, 0x00, 0xa2, 0x20, 0x28, 0xb4, 0x15, 0xa2, 0x2b, 0x37, 0xe5, 0x24, 0x39, 0x49, 0x46,
	0x92, 0x4c, 0x9c, 0x99, 0x88, 0xf6, 0x1d, 0x7c, 0x21, 0x9f, 0xee, 0x32, 0x27, 0xb9, 0xb7, 0x9b,
	0x5b, 0xb8, 0xbb, 0x2f, 0xdf, 0xf7, 0xfb, 0x72, 0x4e, 0x38, 0x81, 0x95, 0xb1, 0x4a, 0x63, 0x41,
	0x51, 0xab, 0x95, 0x55, 0xe2, 0x4d, 0xaa, 0xea, 0x28, 0x55, 0x8d, 0x95, 0x4d, 0x67, 0x28, 0x8d,
	0x7e, 0x93, 0x96, 0xb9, 0xc4, 0xa4, 0xa2, 0x0c, 0x2d, 0x1a, 0xab, 0xbb, 0xd4, 0x76, 0x9a, 0x4c,
	0x34, 0xd4, 0xd6, 0x0b, 0x6c, 0x65, 0xdf, 0x0d, 0xff, 0x79, 0x30, 0x3f, 0x76, 0x16, 0xad, 0x54,
	0x8d, 0xd8, 0xc0, 0xa2, 0xc1, 0x9a, 0x4c, 0x8b, 0x29, 0x05, 0xde, 0xce, 0xdb, 0x2f, 0xe3, 0xab,
	0x21, 0x52, 0x58, 0x55, 0xaa, 0x38, 0x63, 0x96, 0x9d, 0xa9, 0xb1, 0xfa, 0x6f, 0x30, 0xda, 0x79,
	0x7b, 0xff, 0xed, 0xfb, 0xe8, 0xa9, 0xe3, 0xdd, 0xd4, 0x83, 0x2a, 0x3e, 0x64, 0xd9, 0x27, 0xd7,
	0x8f, 0xe9, 0x57, 0x47, 0xc6, 0xc6, 0x7e, 0x75, 0xf5, 0xc2, 0x0d, 0xcc, 0x0f, 0x84, 0xf9, 0x49,
	0x65, 0x24, 0x9e, 0xc3, 0xb8, 0xb6, 0xe5, 0xb0, 0x88, 0x93, 0x2e, 0xfd, 0xae, 0x89, 0x6e, 0xa4,
	0x5b, 0xf0, 0x0f, 0xaa, 0x70, 0xc0, 0x67, 0x34, 0xe5, 0x23, 0x40, 0x08, 0xc0, 0x53, 0xbe, 0x34,
	0x19, 0xfd, 0x11, 0x2f, 0xe0, 0x99, 0x74, 0x82, 0x89, 0x71, 0xdc, 0x3f, 0x84, 0x3b, 0x80, 0xaf,
	0xc9, 0x4f, 0x4a, 0xed, 0x37, 0x79, 0x21, 0x21, 0x60, 0x62, 0xe4, 0x85, 0x06, 0x84, 0x75, 0xf8,
	0xdf, 0x83, 0xd9, 0x11, 0x5b, 0x5e, 0x62, 0x0b, 0x7e, 0x45, 0xb9, 0x3d, 0x37, 0x5d, 0x9d, 0x90,
	0x1e, 0x30, 0x70, 0xd6, 0x89, 0x1d, 0xf1, 0x1a, 0x96, 0x5a, 0x16, 0xe5, 0x03, 0x31, 0x62, 0xc2,
	0x67, 0x6f, 0x40, 0x5e, 0xc2, 0x82, 0xdf, 0x51, 0xa2, 0x29, 0x83, 0x31, 0x6f, 0x3b, 0x77, 0x06,
	0x7f, 0xc4, 0x2b, 0x80, 0xbe, 0xcf, 0xe9, 0xa4, 0xbf, 0x09, 0x3b, 0x1c, 0x73, 0x17, 0xf3, 0x3e,
	0x9d, 0xde, 0x77, 0x31, 0xe7, 0x50, 0xc0, 0xa4, 0x45, 0x5b, 0x06, 0x33, 0xf6, 0x59, 0x7f, 0x5c,
	0xff, 0x08, 0x6e, 0xdd, 0x27, 0x99, 0xf2, 0x2f, 0xf1, 0xee, 0x2e, 0x00, 0x00, 0xff, 0xff, 0xea,
	0xf4, 0x48, 0xb2, 0x5f, 0x02, 0x00, 0x00,
}
