// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LogType int32

const (
	LogType_STRUCT_TYPE_LOG          LogType = 0
	LogType_STRUCT_TYPE_MUTATION_LOG LogType = 1
	LogType_STRUCT_TYPE_TREEHEAD_LOG LogType = 2
)

var LogType_name = map[int32]string{
	0: "STRUCT_TYPE_LOG",
	1: "STRUCT_TYPE_MUTATION_LOG",
	2: "STRUCT_TYPE_TREEHEAD_LOG",
}
var LogType_value = map[string]int32{
	"STRUCT_TYPE_LOG":          0,
	"STRUCT_TYPE_MUTATION_LOG": 1,
	"STRUCT_TYPE_TREEHEAD_LOG": 2,
}

func (x LogType) String() string {
	return proto.EnumName(LogType_name, int32(x))
}
func (LogType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type EntryFormat int32

const (
	EntryFormat_ENTRY_FORMAT_RAW           EntryFormat = 0
	EntryFormat_ENTRY_FORMAT_JSON          EntryFormat = 1
	EntryFormat_ENTRY_FORMAT_JSON_REDACTED EntryFormat = 2
)

var EntryFormat_name = map[int32]string{
	0: "ENTRY_FORMAT_RAW",
	1: "ENTRY_FORMAT_JSON",
	2: "ENTRY_FORMAT_JSON_REDACTED",
}
var EntryFormat_value = map[string]int32{
	"ENTRY_FORMAT_RAW":           0,
	"ENTRY_FORMAT_JSON":          1,
	"ENTRY_FORMAT_JSON_REDACTED": 2,
}

func (x EntryFormat) String() string {
	return proto.EnumName(EntryFormat_name, int32(x))
}
func (EntryFormat) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type MapMutationAction int32

const (
	MapMutationAction_MAP_MUTATION_SET    MapMutationAction = 0
	MapMutationAction_MAP_MUTATION_DELETE MapMutationAction = 1
	MapMutationAction_MAP_MUTATION_UPDATE MapMutationAction = 2
)

var MapMutationAction_name = map[int32]string{
	0: "MAP_MUTATION_SET",
	1: "MAP_MUTATION_DELETE",
	2: "MAP_MUTATION_UPDATE",
}
var MapMutationAction_value = map[string]int32{
	"MAP_MUTATION_SET":    0,
	"MAP_MUTATION_DELETE": 1,
	"MAP_MUTATION_UPDATE": 2,
}

func (x MapMutationAction) String() string {
	return proto.EnumName(MapMutationAction_name, int32(x))
}
func (MapMutationAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type AccountRef struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
}

func (m *AccountRef) Reset()                    { *m = AccountRef{} }
func (m *AccountRef) String() string            { return proto.CompactTextString(m) }
func (*AccountRef) ProtoMessage()               {}
func (*AccountRef) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *AccountRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountRef) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type LogRef struct {
	Account *AccountRef `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	LogType LogType     `protobuf:"varint,2,opt,name=log_type,json=logType,enum=continusec.verifiabledatastructures.api.LogType" json:"log_type,omitempty"`
	Name    string      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *LogRef) Reset()                    { *m = LogRef{} }
func (m *LogRef) String() string            { return proto.CompactTextString(m) }
func (*LogRef) ProtoMessage()               {}
func (*LogRef) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LogRef) GetAccount() *AccountRef {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *LogRef) GetLogType() LogType {
	if m != nil {
		return m.LogType
	}
	return LogType_STRUCT_TYPE_LOG
}

func (m *LogRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MapRef struct {
	Account *AccountRef `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Name    string      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *MapRef) Reset()                    { *m = MapRef{} }
func (m *MapRef) String() string            { return proto.CompactTextString(m) }
func (*MapRef) ProtoMessage()               {}
func (*MapRef) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *MapRef) GetAccount() *AccountRef {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *MapRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LogCreateRequest struct {
	Log *LogRef `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
}

func (m *LogCreateRequest) Reset()                    { *m = LogCreateRequest{} }
func (m *LogCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*LogCreateRequest) ProtoMessage()               {}
func (*LogCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *LogCreateRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

type LogCreateResponse struct {
}

func (m *LogCreateResponse) Reset()                    { *m = LogCreateResponse{} }
func (m *LogCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*LogCreateResponse) ProtoMessage()               {}
func (*LogCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type LogDeleteRequest struct {
	Log *LogRef `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
}

func (m *LogDeleteRequest) Reset()                    { *m = LogDeleteRequest{} }
func (m *LogDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*LogDeleteRequest) ProtoMessage()               {}
func (*LogDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *LogDeleteRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

type LogDeleteResponse struct {
}

func (m *LogDeleteResponse) Reset()                    { *m = LogDeleteResponse{} }
func (m *LogDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*LogDeleteResponse) ProtoMessage()               {}
func (*LogDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

type LogListRequest struct {
	Account *AccountRef `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *LogListRequest) Reset()                    { *m = LogListRequest{} }
func (m *LogListRequest) String() string            { return proto.CompactTextString(m) }
func (*LogListRequest) ProtoMessage()               {}
func (*LogListRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *LogListRequest) GetAccount() *AccountRef {
	if m != nil {
		return m.Account
	}
	return nil
}

type LogInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LogInfo) Reset()                    { *m = LogInfo{} }
func (m *LogInfo) String() string            { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()               {}
func (*LogInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *LogInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LogListResponse struct {
	Logs []*LogInfo `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
}

func (m *LogListResponse) Reset()                    { *m = LogListResponse{} }
func (m *LogListResponse) String() string            { return proto.CompactTextString(m) }
func (*LogListResponse) ProtoMessage()               {}
func (*LogListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *LogListResponse) GetLogs() []*LogInfo {
	if m != nil {
		return m.Logs
	}
	return nil
}

type MapCreateRequest struct {
	Map *MapRef `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
}

func (m *MapCreateRequest) Reset()                    { *m = MapCreateRequest{} }
func (m *MapCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*MapCreateRequest) ProtoMessage()               {}
func (*MapCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *MapCreateRequest) GetMap() *MapRef {
	if m != nil {
		return m.Map
	}
	return nil
}

type MapCreateResponse struct {
}

func (m *MapCreateResponse) Reset()                    { *m = MapCreateResponse{} }
func (m *MapCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*MapCreateResponse) ProtoMessage()               {}
func (*MapCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

type MapDeleteRequest struct {
	Map *MapRef `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
}

func (m *MapDeleteRequest) Reset()                    { *m = MapDeleteRequest{} }
func (m *MapDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*MapDeleteRequest) ProtoMessage()               {}
func (*MapDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *MapDeleteRequest) GetMap() *MapRef {
	if m != nil {
		return m.Map
	}
	return nil
}

type MapDeleteResponse struct {
}

func (m *MapDeleteResponse) Reset()                    { *m = MapDeleteResponse{} }
func (m *MapDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*MapDeleteResponse) ProtoMessage()               {}
func (*MapDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

type MapListRequest struct {
	Account *AccountRef `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *MapListRequest) Reset()                    { *m = MapListRequest{} }
func (m *MapListRequest) String() string            { return proto.CompactTextString(m) }
func (*MapListRequest) ProtoMessage()               {}
func (*MapListRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *MapListRequest) GetAccount() *AccountRef {
	if m != nil {
		return m.Account
	}
	return nil
}

type MapInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MapInfo) Reset()                    { *m = MapInfo{} }
func (m *MapInfo) String() string            { return proto.CompactTextString(m) }
func (*MapInfo) ProtoMessage()               {}
func (*MapInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *MapInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MapListResponse struct {
	Maps []*MapInfo `protobuf:"bytes,1,rep,name=Maps" json:"Maps,omitempty"`
}

func (m *MapListResponse) Reset()                    { *m = MapListResponse{} }
func (m *MapListResponse) String() string            { return proto.CompactTextString(m) }
func (*MapListResponse) ProtoMessage()               {}
func (*MapListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *MapListResponse) GetMaps() []*MapInfo {
	if m != nil {
		return m.Maps
	}
	return nil
}

type LogTreeHashRequest struct {
	Log      *LogRef `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	TreeSize int64   `protobuf:"varint,2,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
}

func (m *LogTreeHashRequest) Reset()                    { *m = LogTreeHashRequest{} }
func (m *LogTreeHashRequest) String() string            { return proto.CompactTextString(m) }
func (*LogTreeHashRequest) ProtoMessage()               {}
func (*LogTreeHashRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *LogTreeHashRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *LogTreeHashRequest) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

type LogTreeHashResponse struct {
	TreeSize int64  `protobuf:"varint,1,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	RootHash []byte `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
}

func (m *LogTreeHashResponse) Reset()                    { *m = LogTreeHashResponse{} }
func (m *LogTreeHashResponse) String() string            { return proto.CompactTextString(m) }
func (*LogTreeHashResponse) ProtoMessage()               {}
func (*LogTreeHashResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *LogTreeHashResponse) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *LogTreeHashResponse) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

type MapTreeHashRequest struct {
	Map      *MapRef `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
	TreeSize int64   `protobuf:"varint,2,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
}

func (m *MapTreeHashRequest) Reset()                    { *m = MapTreeHashRequest{} }
func (m *MapTreeHashRequest) String() string            { return proto.CompactTextString(m) }
func (*MapTreeHashRequest) ProtoMessage()               {}
func (*MapTreeHashRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *MapTreeHashRequest) GetMap() *MapRef {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *MapTreeHashRequest) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

type MapTreeHashResponse struct {
	RootHash    []byte               `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	MutationLog *LogTreeHashResponse `protobuf:"bytes,2,opt,name=mutation_log,json=mutationLog" json:"mutation_log,omitempty"`
}

func (m *MapTreeHashResponse) Reset()                    { *m = MapTreeHashResponse{} }
func (m *MapTreeHashResponse) String() string            { return proto.CompactTextString(m) }
func (*MapTreeHashResponse) ProtoMessage()               {}
func (*MapTreeHashResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *MapTreeHashResponse) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *MapTreeHashResponse) GetMutationLog() *LogTreeHashResponse {
	if m != nil {
		return m.MutationLog
	}
	return nil
}

type LogInclusionProofRequest struct {
	Log      *LogRef `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	TreeSize int64   `protobuf:"varint,2,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	// One of:
	MtlHash   []byte `protobuf:"bytes,3,opt,name=mtl_hash,json=mtlHash,proto3" json:"mtl_hash,omitempty"`
	LeafIndex int64  `protobuf:"varint,4,opt,name=leaf_index,json=leafIndex" json:"leaf_index,omitempty"`
}

func (m *LogInclusionProofRequest) Reset()                    { *m = LogInclusionProofRequest{} }
func (m *LogInclusionProofRequest) String() string            { return proto.CompactTextString(m) }
func (*LogInclusionProofRequest) ProtoMessage()               {}
func (*LogInclusionProofRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{21} }

func (m *LogInclusionProofRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *LogInclusionProofRequest) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *LogInclusionProofRequest) GetMtlHash() []byte {
	if m != nil {
		return m.MtlHash
	}
	return nil
}

func (m *LogInclusionProofRequest) GetLeafIndex() int64 {
	if m != nil {
		return m.LeafIndex
	}
	return 0
}

type LogInclusionProofResponse struct {
	TreeSize  int64    `protobuf:"varint,1,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	LeafIndex int64    `protobuf:"varint,2,opt,name=leaf_index,json=leafIndex" json:"leaf_index,omitempty"`
	AuditPath [][]byte `protobuf:"bytes,3,rep,name=audit_path,json=auditPath,proto3" json:"audit_path,omitempty"`
}

func (m *LogInclusionProofResponse) Reset()                    { *m = LogInclusionProofResponse{} }
func (m *LogInclusionProofResponse) String() string            { return proto.CompactTextString(m) }
func (*LogInclusionProofResponse) ProtoMessage()               {}
func (*LogInclusionProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{22} }

func (m *LogInclusionProofResponse) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *LogInclusionProofResponse) GetLeafIndex() int64 {
	if m != nil {
		return m.LeafIndex
	}
	return 0
}

func (m *LogInclusionProofResponse) GetAuditPath() [][]byte {
	if m != nil {
		return m.AuditPath
	}
	return nil
}

type LogConsistencyProofRequest struct {
	Log      *LogRef `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	FromSize int64   `protobuf:"varint,2,opt,name=from_size,json=fromSize" json:"from_size,omitempty"`
	TreeSize int64   `protobuf:"varint,3,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
}

func (m *LogConsistencyProofRequest) Reset()                    { *m = LogConsistencyProofRequest{} }
func (m *LogConsistencyProofRequest) String() string            { return proto.CompactTextString(m) }
func (*LogConsistencyProofRequest) ProtoMessage()               {}
func (*LogConsistencyProofRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{23} }

func (m *LogConsistencyProofRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *LogConsistencyProofRequest) GetFromSize() int64 {
	if m != nil {
		return m.FromSize
	}
	return 0
}

func (m *LogConsistencyProofRequest) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

type LogConsistencyProofResponse struct {
	FromSize  int64    `protobuf:"varint,1,opt,name=from_size,json=fromSize" json:"from_size,omitempty"`
	TreeSize  int64    `protobuf:"varint,2,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	AuditPath [][]byte `protobuf:"bytes,3,rep,name=audit_path,json=auditPath,proto3" json:"audit_path,omitempty"`
}

func (m *LogConsistencyProofResponse) Reset()                    { *m = LogConsistencyProofResponse{} }
func (m *LogConsistencyProofResponse) String() string            { return proto.CompactTextString(m) }
func (*LogConsistencyProofResponse) ProtoMessage()               {}
func (*LogConsistencyProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{24} }

func (m *LogConsistencyProofResponse) GetFromSize() int64 {
	if m != nil {
		return m.FromSize
	}
	return 0
}

func (m *LogConsistencyProofResponse) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *LogConsistencyProofResponse) GetAuditPath() [][]byte {
	if m != nil {
		return m.AuditPath
	}
	return nil
}

type HashableData struct {
	Format EntryFormat `protobuf:"varint,1,opt,name=format,enum=continusec.verifiabledatastructures.api.EntryFormat" json:"format,omitempty"`
	Value  []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *HashableData) Reset()                    { *m = HashableData{} }
func (m *HashableData) String() string            { return proto.CompactTextString(m) }
func (*HashableData) ProtoMessage()               {}
func (*HashableData) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{25} }

func (m *HashableData) GetFormat() EntryFormat {
	if m != nil {
		return m.Format
	}
	return EntryFormat_ENTRY_FORMAT_RAW
}

func (m *HashableData) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type LogAddEntryRequest struct {
	Log  *LogRef       `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	Data *HashableData `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *LogAddEntryRequest) Reset()                    { *m = LogAddEntryRequest{} }
func (m *LogAddEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*LogAddEntryRequest) ProtoMessage()               {}
func (*LogAddEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{26} }

func (m *LogAddEntryRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *LogAddEntryRequest) GetData() *HashableData {
	if m != nil {
		return m.Data
	}
	return nil
}

type LogAddEntryResponse struct {
	LeafHash []byte `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
}

func (m *LogAddEntryResponse) Reset()                    { *m = LogAddEntryResponse{} }
func (m *LogAddEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*LogAddEntryResponse) ProtoMessage()               {}
func (*LogAddEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{27} }

func (m *LogAddEntryResponse) GetLeafHash() []byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

type MapSetValueRequest struct {
	Map          *MapRef           `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
	Action       MapMutationAction `protobuf:"varint,2,opt,name=action,enum=continusec.verifiabledatastructures.api.MapMutationAction" json:"action,omitempty"`
	Key          []byte            `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value        *HashableData     `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	PrevLeafHash []byte            `protobuf:"bytes,5,opt,name=prev_leaf_hash,json=prevLeafHash,proto3" json:"prev_leaf_hash,omitempty"`
}

func (m *MapSetValueRequest) Reset()                    { *m = MapSetValueRequest{} }
func (m *MapSetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*MapSetValueRequest) ProtoMessage()               {}
func (*MapSetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{28} }

func (m *MapSetValueRequest) GetMap() *MapRef {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *MapSetValueRequest) GetAction() MapMutationAction {
	if m != nil {
		return m.Action
	}
	return MapMutationAction_MAP_MUTATION_SET
}

func (m *MapSetValueRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MapSetValueRequest) GetValue() *HashableData {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MapSetValueRequest) GetPrevLeafHash() []byte {
	if m != nil {
		return m.PrevLeafHash
	}
	return nil
}

type MapSetValueResponse struct {
	LeafHash []byte `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
}

func (m *MapSetValueResponse) Reset()                    { *m = MapSetValueResponse{} }
func (m *MapSetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*MapSetValueResponse) ProtoMessage()               {}
func (*MapSetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{29} }

func (m *MapSetValueResponse) GetLeafHash() []byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

type MapGetValueRequest struct {
	Map      *MapRef `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
	TreeSize int64   `protobuf:"varint,2,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	Key      []byte  `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *MapGetValueRequest) Reset()                    { *m = MapGetValueRequest{} }
func (m *MapGetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*MapGetValueRequest) ProtoMessage()               {}
func (*MapGetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{30} }

func (m *MapGetValueRequest) GetMap() *MapRef {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *MapGetValueRequest) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *MapGetValueRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type MapGetValueResponse struct {
	TreeSize  int64         `protobuf:"varint,1,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	AuditPath [][]byte      `protobuf:"bytes,2,rep,name=audit_path,json=auditPath,proto3" json:"audit_path,omitempty"`
	Value     *HashableData `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *MapGetValueResponse) Reset()                    { *m = MapGetValueResponse{} }
func (m *MapGetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*MapGetValueResponse) ProtoMessage()               {}
func (*MapGetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{31} }

func (m *MapGetValueResponse) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *MapGetValueResponse) GetAuditPath() [][]byte {
	if m != nil {
		return m.AuditPath
	}
	return nil
}

func (m *MapGetValueResponse) GetValue() *HashableData {
	if m != nil {
		return m.Value
	}
	return nil
}

type LogFetchEntriesRequest struct {
	Log   *LogRef `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	First int64   `protobuf:"varint,2,opt,name=first" json:"first,omitempty"`
	Last  int64   `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`
}

func (m *LogFetchEntriesRequest) Reset()                    { *m = LogFetchEntriesRequest{} }
func (m *LogFetchEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*LogFetchEntriesRequest) ProtoMessage()               {}
func (*LogFetchEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{32} }

func (m *LogFetchEntriesRequest) GetLog() *LogRef {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *LogFetchEntriesRequest) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *LogFetchEntriesRequest) GetLast() int64 {
	if m != nil {
		return m.Last
	}
	return 0
}

type LogFetchEntriesResponse struct {
	Values []*HashableData `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *LogFetchEntriesResponse) Reset()                    { *m = LogFetchEntriesResponse{} }
func (m *LogFetchEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*LogFetchEntriesResponse) ProtoMessage()               {}
func (*LogFetchEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{33} }

func (m *LogFetchEntriesResponse) GetValues() []*HashableData {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountRef)(nil), "continusec.verifiabledatastructures.api.AccountRef")
	proto.RegisterType((*LogRef)(nil), "continusec.verifiabledatastructures.api.LogRef")
	proto.RegisterType((*MapRef)(nil), "continusec.verifiabledatastructures.api.MapRef")
	proto.RegisterType((*LogCreateRequest)(nil), "continusec.verifiabledatastructures.api.LogCreateRequest")
	proto.RegisterType((*LogCreateResponse)(nil), "continusec.verifiabledatastructures.api.LogCreateResponse")
	proto.RegisterType((*LogDeleteRequest)(nil), "continusec.verifiabledatastructures.api.LogDeleteRequest")
	proto.RegisterType((*LogDeleteResponse)(nil), "continusec.verifiabledatastructures.api.LogDeleteResponse")
	proto.RegisterType((*LogListRequest)(nil), "continusec.verifiabledatastructures.api.LogListRequest")
	proto.RegisterType((*LogInfo)(nil), "continusec.verifiabledatastructures.api.LogInfo")
	proto.RegisterType((*LogListResponse)(nil), "continusec.verifiabledatastructures.api.LogListResponse")
	proto.RegisterType((*MapCreateRequest)(nil), "continusec.verifiabledatastructures.api.MapCreateRequest")
	proto.RegisterType((*MapCreateResponse)(nil), "continusec.verifiabledatastructures.api.MapCreateResponse")
	proto.RegisterType((*MapDeleteRequest)(nil), "continusec.verifiabledatastructures.api.MapDeleteRequest")
	proto.RegisterType((*MapDeleteResponse)(nil), "continusec.verifiabledatastructures.api.MapDeleteResponse")
	proto.RegisterType((*MapListRequest)(nil), "continusec.verifiabledatastructures.api.MapListRequest")
	proto.RegisterType((*MapInfo)(nil), "continusec.verifiabledatastructures.api.MapInfo")
	proto.RegisterType((*MapListResponse)(nil), "continusec.verifiabledatastructures.api.MapListResponse")
	proto.RegisterType((*LogTreeHashRequest)(nil), "continusec.verifiabledatastructures.api.LogTreeHashRequest")
	proto.RegisterType((*LogTreeHashResponse)(nil), "continusec.verifiabledatastructures.api.LogTreeHashResponse")
	proto.RegisterType((*MapTreeHashRequest)(nil), "continusec.verifiabledatastructures.api.MapTreeHashRequest")
	proto.RegisterType((*MapTreeHashResponse)(nil), "continusec.verifiabledatastructures.api.MapTreeHashResponse")
	proto.RegisterType((*LogInclusionProofRequest)(nil), "continusec.verifiabledatastructures.api.LogInclusionProofRequest")
	proto.RegisterType((*LogInclusionProofResponse)(nil), "continusec.verifiabledatastructures.api.LogInclusionProofResponse")
	proto.RegisterType((*LogConsistencyProofRequest)(nil), "continusec.verifiabledatastructures.api.LogConsistencyProofRequest")
	proto.RegisterType((*LogConsistencyProofResponse)(nil), "continusec.verifiabledatastructures.api.LogConsistencyProofResponse")
	proto.RegisterType((*HashableData)(nil), "continusec.verifiabledatastructures.api.HashableData")
	proto.RegisterType((*LogAddEntryRequest)(nil), "continusec.verifiabledatastructures.api.LogAddEntryRequest")
	proto.RegisterType((*LogAddEntryResponse)(nil), "continusec.verifiabledatastructures.api.LogAddEntryResponse")
	proto.RegisterType((*MapSetValueRequest)(nil), "continusec.verifiabledatastructures.api.MapSetValueRequest")
	proto.RegisterType((*MapSetValueResponse)(nil), "continusec.verifiabledatastructures.api.MapSetValueResponse")
	proto.RegisterType((*MapGetValueRequest)(nil), "continusec.verifiabledatastructures.api.MapGetValueRequest")
	proto.RegisterType((*MapGetValueResponse)(nil), "continusec.verifiabledatastructures.api.MapGetValueResponse")
	proto.RegisterType((*LogFetchEntriesRequest)(nil), "continusec.verifiabledatastructures.api.LogFetchEntriesRequest")
	proto.RegisterType((*LogFetchEntriesResponse)(nil), "continusec.verifiabledatastructures.api.LogFetchEntriesResponse")
	proto.RegisterEnum("continusec.verifiabledatastructures.api.LogType", LogType_name, LogType_value)
	proto.RegisterEnum("continusec.verifiabledatastructures.api.EntryFormat", EntryFormat_name, EntryFormat_value)
	proto.RegisterEnum("continusec.verifiabledatastructures.api.MapMutationAction", MapMutationAction_name, MapMutationAction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VerifiableDataStructuresService service

type VerifiableDataStructuresServiceClient interface {
	LogCreate(ctx context.Context, in *LogCreateRequest, opts ...grpc.CallOption) (*LogCreateResponse, error)
	LogDelete(ctx context.Context, in *LogDeleteRequest, opts ...grpc.CallOption) (*LogDeleteResponse, error)
	LogList(ctx context.Context, in *LogListRequest, opts ...grpc.CallOption) (*LogListResponse, error)
	LogAddEntry(ctx context.Context, in *LogAddEntryRequest, opts ...grpc.CallOption) (*LogAddEntryResponse, error)
	LogFetchEntries(ctx context.Context, in *LogFetchEntriesRequest, opts ...grpc.CallOption) (*LogFetchEntriesResponse, error)
	LogTreeHash(ctx context.Context, in *LogTreeHashRequest, opts ...grpc.CallOption) (*LogTreeHashResponse, error)
	LogInclusionProof(ctx context.Context, in *LogInclusionProofRequest, opts ...grpc.CallOption) (*LogInclusionProofResponse, error)
	LogConsistencyProof(ctx context.Context, in *LogConsistencyProofRequest, opts ...grpc.CallOption) (*LogConsistencyProofResponse, error)
	MapCreate(ctx context.Context, in *MapCreateRequest, opts ...grpc.CallOption) (*MapCreateResponse, error)
	MapDelete(ctx context.Context, in *MapDeleteRequest, opts ...grpc.CallOption) (*MapDeleteResponse, error)
	MapList(ctx context.Context, in *MapListRequest, opts ...grpc.CallOption) (*MapListResponse, error)
	MapSetValue(ctx context.Context, in *MapSetValueRequest, opts ...grpc.CallOption) (*MapSetValueResponse, error)
	MapGetValue(ctx context.Context, in *MapGetValueRequest, opts ...grpc.CallOption) (*MapGetValueResponse, error)
	MapTreeHash(ctx context.Context, in *MapTreeHashRequest, opts ...grpc.CallOption) (*MapTreeHashResponse, error)
}

type verifiableDataStructuresServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerifiableDataStructuresServiceClient(cc *grpc.ClientConn) VerifiableDataStructuresServiceClient {
	return &verifiableDataStructuresServiceClient{cc}
}

func (c *verifiableDataStructuresServiceClient) LogCreate(ctx context.Context, in *LogCreateRequest, opts ...grpc.CallOption) (*LogCreateResponse, error) {
	out := new(LogCreateResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogDelete(ctx context.Context, in *LogDeleteRequest, opts ...grpc.CallOption) (*LogDeleteResponse, error) {
	out := new(LogDeleteResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogList(ctx context.Context, in *LogListRequest, opts ...grpc.CallOption) (*LogListResponse, error) {
	out := new(LogListResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogAddEntry(ctx context.Context, in *LogAddEntryRequest, opts ...grpc.CallOption) (*LogAddEntryResponse, error) {
	out := new(LogAddEntryResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogAddEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogFetchEntries(ctx context.Context, in *LogFetchEntriesRequest, opts ...grpc.CallOption) (*LogFetchEntriesResponse, error) {
	out := new(LogFetchEntriesResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogFetchEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogTreeHash(ctx context.Context, in *LogTreeHashRequest, opts ...grpc.CallOption) (*LogTreeHashResponse, error) {
	out := new(LogTreeHashResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogTreeHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogInclusionProof(ctx context.Context, in *LogInclusionProofRequest, opts ...grpc.CallOption) (*LogInclusionProofResponse, error) {
	out := new(LogInclusionProofResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogInclusionProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) LogConsistencyProof(ctx context.Context, in *LogConsistencyProofRequest, opts ...grpc.CallOption) (*LogConsistencyProofResponse, error) {
	out := new(LogConsistencyProofResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogConsistencyProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) MapCreate(ctx context.Context, in *MapCreateRequest, opts ...grpc.CallOption) (*MapCreateResponse, error) {
	out := new(MapCreateResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) MapDelete(ctx context.Context, in *MapDeleteRequest, opts ...grpc.CallOption) (*MapDeleteResponse, error) {
	out := new(MapDeleteResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) MapList(ctx context.Context, in *MapListRequest, opts ...grpc.CallOption) (*MapListResponse, error) {
	out := new(MapListResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) MapSetValue(ctx context.Context, in *MapSetValueRequest, opts ...grpc.CallOption) (*MapSetValueResponse, error) {
	out := new(MapSetValueResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapSetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) MapGetValue(ctx context.Context, in *MapGetValueRequest, opts ...grpc.CallOption) (*MapGetValueResponse, error) {
	out := new(MapGetValueResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapGetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifiableDataStructuresServiceClient) MapTreeHash(ctx context.Context, in *MapTreeHashRequest, opts ...grpc.CallOption) (*MapTreeHashResponse, error) {
	out := new(MapTreeHashResponse)
	err := grpc.Invoke(ctx, "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapTreeHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VerifiableDataStructuresService service

type VerifiableDataStructuresServiceServer interface {
	LogCreate(context.Context, *LogCreateRequest) (*LogCreateResponse, error)
	LogDelete(context.Context, *LogDeleteRequest) (*LogDeleteResponse, error)
	LogList(context.Context, *LogListRequest) (*LogListResponse, error)
	LogAddEntry(context.Context, *LogAddEntryRequest) (*LogAddEntryResponse, error)
	LogFetchEntries(context.Context, *LogFetchEntriesRequest) (*LogFetchEntriesResponse, error)
	LogTreeHash(context.Context, *LogTreeHashRequest) (*LogTreeHashResponse, error)
	LogInclusionProof(context.Context, *LogInclusionProofRequest) (*LogInclusionProofResponse, error)
	LogConsistencyProof(context.Context, *LogConsistencyProofRequest) (*LogConsistencyProofResponse, error)
	MapCreate(context.Context, *MapCreateRequest) (*MapCreateResponse, error)
	MapDelete(context.Context, *MapDeleteRequest) (*MapDeleteResponse, error)
	MapList(context.Context, *MapListRequest) (*MapListResponse, error)
	MapSetValue(context.Context, *MapSetValueRequest) (*MapSetValueResponse, error)
	MapGetValue(context.Context, *MapGetValueRequest) (*MapGetValueResponse, error)
	MapTreeHash(context.Context, *MapTreeHashRequest) (*MapTreeHashResponse, error)
}

func RegisterVerifiableDataStructuresServiceServer(s *grpc.Server, srv VerifiableDataStructuresServiceServer) {
	s.RegisterService(&_VerifiableDataStructuresService_serviceDesc, srv)
}

func _VerifiableDataStructuresService_LogCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogCreate(ctx, req.(*LogCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogDelete(ctx, req.(*LogDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogList(ctx, req.(*LogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogAddEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogAddEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogAddEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogAddEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogAddEntry(ctx, req.(*LogAddEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogFetchEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogFetchEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogFetchEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogFetchEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogFetchEntries(ctx, req.(*LogFetchEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogTreeHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogTreeHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogTreeHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogTreeHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogTreeHash(ctx, req.(*LogTreeHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogInclusionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInclusionProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogInclusionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogInclusionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogInclusionProof(ctx, req.(*LogInclusionProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_LogConsistencyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogConsistencyProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).LogConsistencyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/LogConsistencyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).LogConsistencyProof(ctx, req.(*LogConsistencyProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_MapCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).MapCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).MapCreate(ctx, req.(*MapCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_MapDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).MapDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).MapDelete(ctx, req.(*MapDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_MapList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).MapList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).MapList(ctx, req.(*MapListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_MapSetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapSetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).MapSetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapSetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).MapSetValue(ctx, req.(*MapSetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_MapGetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapGetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).MapGetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapGetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).MapGetValue(ctx, req.(*MapGetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifiableDataStructuresService_MapTreeHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapTreeHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableDataStructuresServiceServer).MapTreeHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.verifiabledatastructures.api.VerifiableDataStructuresService/MapTreeHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableDataStructuresServiceServer).MapTreeHash(ctx, req.(*MapTreeHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerifiableDataStructuresService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "continusec.verifiabledatastructures.api.VerifiableDataStructuresService",
	HandlerType: (*VerifiableDataStructuresServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogCreate",
			Handler:    _VerifiableDataStructuresService_LogCreate_Handler,
		},
		{
			MethodName: "LogDelete",
			Handler:    _VerifiableDataStructuresService_LogDelete_Handler,
		},
		{
			MethodName: "LogList",
			Handler:    _VerifiableDataStructuresService_LogList_Handler,
		},
		{
			MethodName: "LogAddEntry",
			Handler:    _VerifiableDataStructuresService_LogAddEntry_Handler,
		},
		{
			MethodName: "LogFetchEntries",
			Handler:    _VerifiableDataStructuresService_LogFetchEntries_Handler,
		},
		{
			MethodName: "LogTreeHash",
			Handler:    _VerifiableDataStructuresService_LogTreeHash_Handler,
		},
		{
			MethodName: "LogInclusionProof",
			Handler:    _VerifiableDataStructuresService_LogInclusionProof_Handler,
		},
		{
			MethodName: "LogConsistencyProof",
			Handler:    _VerifiableDataStructuresService_LogConsistencyProof_Handler,
		},
		{
			MethodName: "MapCreate",
			Handler:    _VerifiableDataStructuresService_MapCreate_Handler,
		},
		{
			MethodName: "MapDelete",
			Handler:    _VerifiableDataStructuresService_MapDelete_Handler,
		},
		{
			MethodName: "MapList",
			Handler:    _VerifiableDataStructuresService_MapList_Handler,
		},
		{
			MethodName: "MapSetValue",
			Handler:    _VerifiableDataStructuresService_MapSetValue_Handler,
		},
		{
			MethodName: "MapGetValue",
			Handler:    _VerifiableDataStructuresService_MapGetValue_Handler,
		},
		{
			MethodName: "MapTreeHash",
			Handler:    _VerifiableDataStructuresService_MapTreeHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x58, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0x36, 0x29, 0x47, 0xb6, 0xc7, 0x86, 0xa3, 0xac, 0xf3, 0xfb, 0x45, 0x51, 0x9a, 0x36, 0x20,
	0x0a, 0x34, 0xc8, 0xc1, 0x2d, 0x9c, 0x06, 0x6d, 0xd3, 0x00, 0x2d, 0x63, 0x31, 0x8e, 0x1b, 0x32,
	0x36, 0x28, 0x3a, 0x41, 0xd2, 0x03, 0xb1, 0x91, 0x56, 0x32, 0x11, 0x8a, 0xcb, 0x92, 0x2b, 0xa3,
	0xce, 0xa1, 0xa7, 0xb6, 0x87, 0x5e, 0x0b, 0x14, 0x28, 0x50, 0xf4, 0x90, 0x27, 0xe8, 0xa1, 0x87,
	0xbe, 0x4b, 0x5f, 0xa6, 0xd8, 0x25, 0x25, 0xfe, 0x91, 0x2a, 0x68, 0x25, 0xb9, 0x37, 0x6a, 0xa9,
	0xf9, 0xe6, 0x9b, 0x6f, 0x76, 0x86, 0xb3, 0x0b, 0x1b, 0x38, 0xf4, 0x76, 0xc3, 0x88, 0x32, 0x8a,
	0x3e, 0x68, 0xd3, 0x80, 0x79, 0xc1, 0x20, 0x26, 0xed, 0xdd, 0x33, 0x12, 0x79, 0x5d, 0x0f, 0xbf,
	0xf2, 0x49, 0x07, 0x33, 0x1c, 0xb3, 0x68, 0xd0, 0x66, 0x83, 0x88, 0xc4, 0xbb, 0x38, 0xf4, 0xb4,
	0x7b, 0x00, 0x7a, 0xbb, 0x4d, 0x07, 0x01, 0xb3, 0x49, 0x17, 0x6d, 0x83, 0xea, 0x75, 0xea, 0xca,
	0x2d, 0xe5, 0xf6, 0x86, 0xad, 0x7a, 0x1d, 0x74, 0x0d, 0xd6, 0x70, 0xe8, 0xb9, 0xaf, 0xc9, 0x79,
	0x5d, 0x15, 0x8b, 0x55, 0x1c, 0x7a, 0x4f, 0xc8, 0xb9, 0xf6, 0x97, 0x02, 0x55, 0x93, 0xf6, 0xb8,
	0x8d, 0x05, 0x6b, 0x38, 0x41, 0x10, 0x86, 0x9b, 0x7b, 0x77, 0x77, 0x67, 0x74, 0xbe, 0x9b, 0x79,
	0xb6, 0x87, 0x18, 0xe8, 0x09, 0xac, 0xfb, 0xb4, 0xe7, 0xb2, 0xf3, 0x90, 0x08, 0x9f, 0xdb, 0x7b,
	0x1f, 0xcd, 0x8c, 0x67, 0xd2, 0x9e, 0x73, 0x1e, 0x12, 0x7b, 0xcd, 0x4f, 0x1e, 0x10, 0x82, 0xd5,
	0x00, 0xf7, 0x49, 0xbd, 0x22, 0xc8, 0x8b, 0x67, 0xed, 0x35, 0x54, 0x2d, 0x1c, 0x5e, 0x00, 0xf3,
	0x49, 0xce, 0x4e, 0xa0, 0x66, 0xd2, 0xde, 0x7e, 0x44, 0x30, 0x23, 0x36, 0xf9, 0x66, 0x40, 0x62,
	0x86, 0x74, 0xa8, 0xf8, 0xb4, 0x97, 0xba, 0xfc, 0x50, 0x26, 0x38, 0xee, 0x8e, 0xdb, 0x6a, 0x3b,
	0x70, 0x25, 0x07, 0x1b, 0x87, 0x34, 0x88, 0x87, 0xbe, 0x9a, 0xc4, 0x27, 0x17, 0xe0, 0x6b, 0x08,
	0x9b, 0xfa, 0x72, 0x61, 0xdb, 0xa4, 0x3d, 0xd3, 0x8b, 0xd9, 0xd0, 0xd3, 0x72, 0xc5, 0xd4, 0x6e,
	0xc2, 0x9a, 0x49, 0x7b, 0x87, 0x41, 0x97, 0x8e, 0x74, 0x55, 0x72, 0xba, 0x3e, 0x87, 0xcb, 0x23,
	0xff, 0x09, 0x25, 0xd4, 0x84, 0x55, 0x9f, 0xf6, 0xe2, 0xba, 0x72, 0xab, 0x72, 0x7b, 0x53, 0x6e,
	0xd3, 0x70, 0x37, 0xb6, 0xb0, 0xe6, 0x22, 0x5a, 0x38, 0x1c, 0x4b, 0x58, 0x1f, 0x87, 0xd2, 0x22,
	0x26, 0xbb, 0xcc, 0xe6, 0xb6, 0x5c, 0xc4, 0x1c, 0x6c, 0x96, 0x30, 0x0b, 0x87, 0x63, 0x09, 0x5b,
	0x8e, 0xaf, 0xf1, 0x84, 0x59, 0x38, 0xbc, 0xd8, 0x84, 0x59, 0x38, 0x9c, 0x96, 0xb0, 0x91, 0xff,
	0x2c, 0x61, 0x16, 0x0e, 0xe5, 0x13, 0x96, 0xba, 0xb1, 0x85, 0xb5, 0xc6, 0x00, 0xf1, 0xb2, 0x8f,
	0x08, 0x79, 0x8c, 0xe3, 0xd3, 0xe5, 0xed, 0x7b, 0x74, 0x03, 0x36, 0x58, 0x44, 0x88, 0x1b, 0x7b,
	0x6f, 0x92, 0x4e, 0x54, 0xb1, 0xd7, 0xf9, 0x42, 0xcb, 0x7b, 0x43, 0xb4, 0x23, 0xd8, 0x29, 0x78,
	0x4d, 0x43, 0x2a, 0xd8, 0x28, 0x45, 0x1b, 0xfe, 0x32, 0xa2, 0x94, 0xb9, 0xa7, 0x38, 0x3e, 0x15,
	0x80, 0x5b, 0xf6, 0x3a, 0x5f, 0xe0, 0x08, 0x3c, 0x0c, 0x0b, 0x87, 0x13, 0xc2, 0x58, 0x70, 0x37,
	0x4c, 0x0f, 0xe3, 0x67, 0x05, 0x76, 0x0a, 0x6e, 0xb3, 0x38, 0x32, 0xaa, 0x4a, 0x91, 0x2a, 0x72,
	0x61, 0xab, 0x3f, 0x60, 0x98, 0x79, 0x34, 0x70, 0xb9, 0xc8, 0xaa, 0x60, 0xf7, 0x40, 0xaa, 0x4b,
	0x97, 0x1c, 0xda, 0x9b, 0x43, 0x44, 0x93, 0xf6, 0xb4, 0x3f, 0x15, 0xa8, 0x8b, 0xaa, 0x6c, 0xfb,
	0x83, 0xd8, 0xa3, 0xc1, 0x71, 0x44, 0x69, 0xf7, 0x3f, 0xca, 0x2c, 0xba, 0x0e, 0xeb, 0x7d, 0xe6,
	0x27, 0x91, 0x57, 0x44, 0xe4, 0x6b, 0x7d, 0xe6, 0x8b, 0xc0, 0x6f, 0x02, 0xf8, 0x04, 0x77, 0x5d,
	0x2f, 0xe8, 0x90, 0x6f, 0xeb, 0xab, 0xc2, 0x70, 0x83, 0xaf, 0x1c, 0xf2, 0x05, 0xed, 0x0c, 0xae,
	0x4f, 0x60, 0x3d, 0xcb, 0xce, 0x28, 0x02, 0xab, 0x25, 0x60, 0xfe, 0x1a, 0x0f, 0x3a, 0x1e, 0x73,
	0x43, 0xcc, 0x38, 0xa9, 0xca, 0xed, 0x2d, 0x7b, 0x43, 0xac, 0x1c, 0x63, 0x76, 0xaa, 0xfd, 0xaa,
	0x40, 0x83, 0x7f, 0x0d, 0x68, 0x10, 0x7b, 0x31, 0x23, 0x41, 0xfb, 0xfc, 0x02, 0x04, 0xeb, 0x46,
	0xb4, 0x5f, 0x10, 0x8c, 0x2f, 0x0c, 0xb7, 0x75, 0x16, 0x59, 0xa5, 0xb4, 0xc1, 0xce, 0xe0, 0xc6,
	0x44, 0x6a, 0x99, 0x2a, 0x19, 0xb0, 0x32, 0x0d, 0x58, 0x1d, 0x97, 0x6c, 0x9a, 0x26, 0x11, 0x6c,
	0xf1, 0x94, 0xf1, 0xd8, 0x9a, 0x98, 0x61, 0x64, 0x42, 0xb5, 0x4b, 0xa3, 0x3e, 0x4e, 0x7a, 0xdd,
	0xf6, 0xde, 0xc7, 0x33, 0xeb, 0x60, 0x04, 0x2c, 0x3a, 0x7f, 0x24, 0x6c, 0xed, 0x14, 0x03, 0x5d,
	0x85, 0x4b, 0x67, 0xd8, 0x1f, 0x90, 0xb4, 0x8a, 0x93, 0x1f, 0xda, 0x5b, 0x45, 0xb4, 0x22, 0xbd,
	0xd3, 0x11, 0x36, 0x4b, 0xd4, 0xff, 0x10, 0x56, 0xf9, 0x3f, 0xd2, 0x4a, 0xbb, 0x37, 0x33, 0x46,
	0x5e, 0x02, 0x5b, 0x40, 0x68, 0x7b, 0xa2, 0x71, 0x65, 0x1c, 0xb3, 0x44, 0x88, 0x1d, 0x98, 0x2f,
	0x78, 0xbe, 0x20, 0x7a, 0xd3, 0x1f, 0xaa, 0x68, 0x4e, 0x2d, 0xc2, 0x9e, 0xf1, 0x40, 0x97, 0xd8,
	0x9c, 0x6c, 0xa8, 0xe2, 0x36, 0x2f, 0xfb, 0x74, 0xd4, 0xbb, 0x2f, 0x83, 0x62, 0xa5, 0x2d, 0x43,
	0x17, 0x08, 0x76, 0x8a, 0x84, 0x6a, 0x50, 0xe1, 0xf3, 0x6a, 0x52, 0xbb, 0xfc, 0x11, 0x3d, 0x19,
	0xa6, 0x6b, 0x75, 0x11, 0xfd, 0x12, 0x0c, 0xf4, 0x3e, 0x6c, 0x87, 0x11, 0x39, 0x73, 0x33, 0xb9,
	0x2e, 0x09, 0x4f, 0x5b, 0x7c, 0xd5, 0x1c, 0x4a, 0xb6, 0x27, 0xfa, 0x6a, 0xa6, 0xd8, 0x2c, 0x32,
	0xff, 0xa8, 0x08, 0x99, 0x0f, 0x96, 0x2f, 0xf3, 0xd4, 0x4a, 0x1a, 0xd3, 0x4b, 0xfb, 0x3d, 0xf9,
	0x2a, 0x1c, 0x4c, 0x60, 0x3f, 0xb5, 0x87, 0xe5, 0x0a, 0x52, 0x2d, 0x15, 0x64, 0x96, 0x83, 0xca,
	0xe2, 0x39, 0xd0, 0x7e, 0x50, 0xe0, 0xff, 0x26, 0xed, 0x3d, 0x22, 0xac, 0x7d, 0xca, 0xf7, 0xb1,
	0x47, 0xe2, 0x25, 0x56, 0xdb, 0x55, 0xb8, 0xd4, 0xf5, 0xa2, 0x98, 0xa5, 0x4a, 0x25, 0x3f, 0xf8,
	0x50, 0xe3, 0xe3, 0x98, 0xa5, 0x1d, 0x4e, 0x3c, 0x6b, 0xa7, 0x70, 0x6d, 0x8c, 0x46, 0xaa, 0x95,
	0x05, 0x55, 0xc1, 0x75, 0x38, 0xde, 0xcc, 0x19, 0x70, 0x0a, 0x72, 0xe7, 0xa5, 0x18, 0x87, 0xc5,
	0x99, 0x66, 0x07, 0x2e, 0xb7, 0x1c, 0xfb, 0x64, 0xdf, 0x71, 0x9d, 0x17, 0xc7, 0x86, 0x6b, 0x1e,
	0x1d, 0xd4, 0x56, 0xd0, 0x3b, 0x50, 0xcf, 0x2f, 0x5a, 0x27, 0x8e, 0xee, 0x1c, 0x1e, 0x3d, 0x15,
	0x6f, 0x95, 0xf2, 0x5b, 0xc7, 0x36, 0x8c, 0xc7, 0x86, 0xde, 0x14, 0x6f, 0xd5, 0x3b, 0x2f, 0x61,
	0x33, 0xd7, 0xe4, 0xd0, 0x55, 0xa8, 0x19, 0x4f, 0x1d, 0xfb, 0x85, 0xfb, 0xe8, 0xc8, 0xb6, 0x74,
	0xc7, 0xb5, 0xf5, 0xe7, 0xb5, 0x15, 0xf4, 0x3f, 0xb8, 0x52, 0x58, 0xfd, 0xaa, 0x75, 0xf4, 0xb4,
	0xa6, 0xa0, 0x77, 0xa1, 0x31, 0xb6, 0xec, 0xda, 0x46, 0x53, 0xdf, 0x77, 0x8c, 0x66, 0x4d, 0xbd,
	0xf3, 0xb5, 0x98, 0x45, 0x8b, 0x95, 0xca, 0x3d, 0x58, 0xfa, 0x71, 0x46, 0xb2, 0x65, 0x38, 0xb5,
	0x15, 0x74, 0x0d, 0x76, 0x0a, 0xab, 0x4d, 0xc3, 0x34, 0x1c, 0xa3, 0xa6, 0x8c, 0xbd, 0x38, 0x39,
	0x6e, 0xea, 0x8e, 0x51, 0x53, 0xf7, 0xfe, 0xbe, 0x0c, 0xef, 0x3d, 0x1b, 0x49, 0xc9, 0xf5, 0x6a,
	0x8d, 0xa4, 0x6c, 0x91, 0xe8, 0xcc, 0x6b, 0x13, 0xf4, 0xbd, 0x02, 0x1b, 0xa3, 0xa3, 0x12, 0xfa,
	0x4c, 0x66, 0x43, 0x14, 0x0e, 0x01, 0x8d, 0xfb, 0xf3, 0x98, 0xa6, 0xc3, 0xf7, 0xca, 0x90, 0x46,
	0x32, 0x94, 0xcb, 0xd1, 0x28, 0x9c, 0x0f, 0xe4, 0x68, 0x94, 0xce, 0x00, 0x2b, 0xe8, 0x3b, 0xb1,
	0x8d, 0xf8, 0x14, 0x8e, 0x3e, 0x91, 0x01, 0xca, 0x9d, 0x1b, 0x1a, 0x9f, 0xca, 0x1b, 0x8e, 0xfc,
	0xff, 0xa4, 0xc0, 0x66, 0xee, 0xf3, 0x83, 0x3e, 0x97, 0xc1, 0x2a, 0x7d, 0x58, 0x1b, 0x0f, 0xe6,
	0x33, 0x1e, 0x91, 0xf9, 0x45, 0x11, 0x87, 0xc8, 0x7c, 0xf9, 0xa2, 0x2f, 0x64, 0x30, 0x27, 0xf4,
	0x9f, 0xc6, 0x97, 0xf3, 0x03, 0x94, 0x55, 0x1a, 0x0e, 0xc9, 0x72, 0x2a, 0x95, 0x8e, 0x10, 0x8d,
	0x85, 0xe6, 0x72, 0x6d, 0x05, 0xfd, 0xa6, 0x88, 0xf3, 0x7f, 0x71, 0xac, 0x45, 0xba, 0xdc, 0xf1,
	0x7a, 0xc2, 0x20, 0xdf, 0x78, 0xb8, 0x08, 0xc4, 0x88, 0xde, 0x5b, 0x45, 0x0c, 0x34, 0xe5, 0x09,
	0x13, 0xed, 0x4b, 0x95, 0xeb, 0xe4, 0xd1, 0xb9, 0xd1, 0x5c, 0x0c, 0xa4, 0x50, 0xfd, 0xa3, 0xe3,
	0xbf, 0x44, 0xf5, 0x97, 0x6f, 0x22, 0x1a, 0xf7, 0xe7, 0x31, 0x2d, 0xd3, 0x90, 0x6e, 0x42, 0xe5,
	0x4b, 0x0a, 0x39, 0x1a, 0x93, 0x9a, 0x50, 0x7a, 0x15, 0x20, 0xd1, 0x84, 0x8a, 0x97, 0x17, 0x12,
	0x4d, 0xa8, 0x74, 0xeb, 0x90, 0x96, 0x57, 0x6e, 0x38, 0x93, 0x28, 0xaf, 0xf1, 0x21, 0x58, 0xa2,
	0xbc, 0x26, 0xcc, 0x83, 0x19, 0x99, 0x83, 0xb9, 0xc8, 0x1c, 0x2c, 0x42, 0xe6, 0xe0, 0x5f, 0xc9,
	0xcc, 0xd1, 0x78, 0xc6, 0xef, 0x2e, 0xe4, 0xc8, 0x8c, 0x37, 0x9e, 0x87, 0xab, 0x2f, 0xd5, 0xf0,
	0xd5, 0xab, 0xaa, 0xb8, 0xcf, 0xbe, 0xfb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0xea, 0x5f,
	0xe0, 0xdc, 0x16, 0x00, 0x00,
}
