//
//
//Copyright 2017 Continusec Pty Ltd
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: configuration.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission int32

const (
	Permission_PERM_NONE                    Permission = 0
	Permission_PERM_ALL_PERMISSIONS         Permission = 1
	Permission_PERM_ACCOUNT_LIST_LOGS       Permission = 2
	Permission_PERM_ACCOUNT_LIST_MAPS       Permission = 3
	Permission_PERM_LOG_CREATE              Permission = 4
	Permission_PERM_LOG_DELETE              Permission = 5
	Permission_PERM_MAP_CREATE              Permission = 6
	Permission_PERM_MAP_DELETE              Permission = 7
	Permission_PERM_LOG_RAW_ADD             Permission = 8
	Permission_PERM_LOG_READ_ENTRY          Permission = 9
	Permission_PERM_LOG_READ_HASH           Permission = 10
	Permission_PERM_LOG_PROVE_INCLUSION     Permission = 11
	Permission_PERM_MAP_SET_VALUE           Permission = 12
	Permission_PERM_MAP_GET_VALUE           Permission = 13
	Permission_PERM_MAP_MUTATION_READ_ENTRY Permission = 14
	Permission_PERM_MAP_MUTATION_READ_HASH  Permission = 15
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "PERM_NONE",
		1:  "PERM_ALL_PERMISSIONS",
		2:  "PERM_ACCOUNT_LIST_LOGS",
		3:  "PERM_ACCOUNT_LIST_MAPS",
		4:  "PERM_LOG_CREATE",
		5:  "PERM_LOG_DELETE",
		6:  "PERM_MAP_CREATE",
		7:  "PERM_MAP_DELETE",
		8:  "PERM_LOG_RAW_ADD",
		9:  "PERM_LOG_READ_ENTRY",
		10: "PERM_LOG_READ_HASH",
		11: "PERM_LOG_PROVE_INCLUSION",
		12: "PERM_MAP_SET_VALUE",
		13: "PERM_MAP_GET_VALUE",
		14: "PERM_MAP_MUTATION_READ_ENTRY",
		15: "PERM_MAP_MUTATION_READ_HASH",
	}
	Permission_value = map[string]int32{
		"PERM_NONE":                    0,
		"PERM_ALL_PERMISSIONS":         1,
		"PERM_ACCOUNT_LIST_LOGS":       2,
		"PERM_ACCOUNT_LIST_MAPS":       3,
		"PERM_LOG_CREATE":              4,
		"PERM_LOG_DELETE":              5,
		"PERM_MAP_CREATE":              6,
		"PERM_MAP_DELETE":              7,
		"PERM_LOG_RAW_ADD":             8,
		"PERM_LOG_READ_ENTRY":          9,
		"PERM_LOG_READ_HASH":           10,
		"PERM_LOG_PROVE_INCLUSION":     11,
		"PERM_MAP_SET_VALUE":           12,
		"PERM_MAP_GET_VALUE":           13,
		"PERM_MAP_MUTATION_READ_ENTRY": 14,
		"PERM_MAP_MUTATION_READ_HASH":  15,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_configuration_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_configuration_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

type ServerConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ServerCertPath           string                 `protobuf:"bytes,1,opt,name=server_cert_path,json=serverCertPath,proto3" json:"server_cert_path,omitempty"`
	ServerKeyPath            string                 `protobuf:"bytes,2,opt,name=server_key_path,json=serverKeyPath,proto3" json:"server_key_path,omitempty"`
	RestListenBind           string                 `protobuf:"bytes,3,opt,name=rest_listen_bind,json=restListenBind,proto3" json:"rest_listen_bind,omitempty"` // e.g. ":8080"
	InsecureServerForTesting bool                   `protobuf:"varint,4,opt,name=insecure_server_for_testing,json=insecureServerForTesting,proto3" json:"insecure_server_for_testing,omitempty"`
	Accounts                 []*ResourceAccount     `protobuf:"bytes,5,rep,name=accounts,proto3" json:"accounts,omitempty"`
	BoltDbPath               string                 `protobuf:"bytes,6,opt,name=bolt_db_path,json=boltDbPath,proto3" json:"bolt_db_path,omitempty"`
	GrpcListenProtocol       string                 `protobuf:"bytes,7,opt,name=grpc_listen_protocol,json=grpcListenProtocol,proto3" json:"grpc_listen_protocol,omitempty"`
	GrpcListenBind           string                 `protobuf:"bytes,8,opt,name=grpc_listen_bind,json=grpcListenBind,proto3" json:"grpc_listen_bind,omitempty"`
	RestServer               bool                   `protobuf:"varint,9,opt,name=rest_server,json=restServer,proto3" json:"rest_server,omitempty"`
	GrpcServer               bool                   `protobuf:"varint,10,opt,name=grpc_server,json=grpcServer,proto3" json:"grpc_server,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetServerCertPath() string {
	if x != nil {
		return x.ServerCertPath
	}
	return ""
}

func (x *ServerConfig) GetServerKeyPath() string {
	if x != nil {
		return x.ServerKeyPath
	}
	return ""
}

func (x *ServerConfig) GetRestListenBind() string {
	if x != nil {
		return x.RestListenBind
	}
	return ""
}

func (x *ServerConfig) GetInsecureServerForTesting() bool {
	if x != nil {
		return x.InsecureServerForTesting
	}
	return false
}

func (x *ServerConfig) GetAccounts() []*ResourceAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ServerConfig) GetBoltDbPath() string {
	if x != nil {
		return x.BoltDbPath
	}
	return ""
}

func (x *ServerConfig) GetGrpcListenProtocol() string {
	if x != nil {
		return x.GrpcListenProtocol
	}
	return ""
}

func (x *ServerConfig) GetGrpcListenBind() string {
	if x != nil {
		return x.GrpcListenBind
	}
	return ""
}

func (x *ServerConfig) GetRestServer() bool {
	if x != nil {
		return x.RestServer
	}
	return false
}

func (x *ServerConfig) GetGrpcServer() bool {
	if x != nil {
		return x.GrpcServer
	}
	return false
}

type AccessPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                                                                           // API key to activate this rule
	NameMatch     string                 `protobuf:"bytes,2,opt,name=name_match,json=nameMatch,proto3" json:"name_match,omitempty"`                                                                  // which logs / maps to match against
	AllowedFields []string               `protobuf:"bytes,3,rep,name=allowed_fields,json=allowedFields,proto3" json:"allowed_fields,omitempty"`                                                      // list of allowed fields names. Must include an '*' for all
	Permissions   []Permission           `protobuf:"varint,4,rep,packed,name=permissions,proto3,enum=com.continusec.verifiabledatastructures.configuration.Permission" json:"permissions,omitempty"` // permissions granted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessPolicy) Reset() {
	*x = AccessPolicy{}
	mi := &file_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPolicy) ProtoMessage() {}

func (x *AccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPolicy.ProtoReflect.Descriptor instead.
func (*AccessPolicy) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *AccessPolicy) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AccessPolicy) GetNameMatch() string {
	if x != nil {
		return x.NameMatch
	}
	return ""
}

func (x *AccessPolicy) GetAllowedFields() []string {
	if x != nil {
		return x.AllowedFields
	}
	return nil
}

func (x *AccessPolicy) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ResourceAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Policy        []*AccessPolicy        `protobuf:"bytes,2,rep,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAccount) Reset() {
	*x = ResourceAccount{}
	mi := &file_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAccount) ProtoMessage() {}

func (x *ResourceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAccount.ProtoReflect.Descriptor instead.
func (*ResourceAccount) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceAccount) GetPolicy() []*AccessPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

var File_configuration_proto protoreflect.FileDescriptor

const file_configuration_proto_rawDesc = "" +
	"\n" +
	"\x13configuration.proto\x125com.continusec.verifiabledatastructures.configuration\"\xed\x03\n" +
	"\fServerConfig\x12(\n" +
	"\x10server_cert_path\x18\x01 \x01(\tR\x0eserverCertPath\x12&\n" +
	"\x0fserver_key_path\x18\x02 \x01(\tR\rserverKeyPath\x12(\n" +
	"\x10rest_listen_bind\x18\x03 \x01(\tR\x0erestListenBind\x12=\n" +
	"\x1binsecure_server_for_testing\x18\x04 \x01(\bR\x18insecureServerForTesting\x12b\n" +
	"\baccounts\x18\x05 \x03(\v2F.com.continusec.verifiabledatastructures.configuration.ResourceAccountR\baccounts\x12 \n" +
	"\fbolt_db_path\x18\x06 \x01(\tR\n" +
	"boltDbPath\x120\n" +
	"\x14grpc_listen_protocol\x18\a \x01(\tR\x12grpcListenProtocol\x12(\n" +
	"\x10grpc_listen_bind\x18\b \x01(\tR\x0egrpcListenBind\x12\x1f\n" +
	"\vrest_server\x18\t \x01(\bR\n" +
	"restServer\x12\x1f\n" +
	"\vgrpc_server\x18\n" +
	" \x01(\bR\n" +
	"grpcServer\"\xd2\x01\n" +
	"\fAccessPolicy\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"name_match\x18\x02 \x01(\tR\tnameMatch\x12%\n" +
	"\x0eallowed_fields\x18\x03 \x03(\tR\rallowedFields\x12c\n" +
	"\vpermissions\x18\x04 \x03(\x0e2A.com.continusec.verifiabledatastructures.configuration.PermissionR\vpermissions\"~\n" +
	"\x0fResourceAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12[\n" +
	"\x06policy\x18\x02 \x03(\v2C.com.continusec.verifiabledatastructures.configuration.AccessPolicyR\x06policy*\x99\x03\n" +
	"\n" +
	"Permission\x12\r\n" +
	"\tPERM_NONE\x10\x00\x12\x18\n" +
	"\x14PERM_ALL_PERMISSIONS\x10\x01\x12\x1a\n" +
	"\x16PERM_ACCOUNT_LIST_LOGS\x10\x02\x12\x1a\n" +
	"\x16PERM_ACCOUNT_LIST_MAPS\x10\x03\x12\x13\n" +
	"\x0fPERM_LOG_CREATE\x10\x04\x12\x13\n" +
	"\x0fPERM_LOG_DELETE\x10\x05\x12\x13\n" +
	"\x0fPERM_MAP_CREATE\x10\x06\x12\x13\n" +
	"\x0fPERM_MAP_DELETE\x10\a\x12\x14\n" +
	"\x10PERM_LOG_RAW_ADD\x10\b\x12\x17\n" +
	"\x13PERM_LOG_READ_ENTRY\x10\t\x12\x16\n" +
	"\x12PERM_LOG_READ_HASH\x10\n" +
	"\x12\x1c\n" +
	"\x18PERM_LOG_PROVE_INCLUSION\x10\v\x12\x16\n" +
	"\x12PERM_MAP_SET_VALUE\x10\f\x12\x16\n" +
	"\x12PERM_MAP_GET_VALUE\x10\r\x12 \n" +
	"\x1cPERM_MAP_MUTATION_READ_ENTRY\x10\x0e\x12\x1f\n" +
	"\x1bPERM_MAP_MUTATION_READ_HASH\x10\x0fB3Z1github.com/continusec/verifiabledatastructures/pbb\x06proto3"

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData []byte
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)))
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_configuration_proto_goTypes = []any{
	(Permission)(0),         // 0: com.continusec.verifiabledatastructures.configuration.Permission
	(*ServerConfig)(nil),    // 1: com.continusec.verifiabledatastructures.configuration.ServerConfig
	(*AccessPolicy)(nil),    // 2: com.continusec.verifiabledatastructures.configuration.AccessPolicy
	(*ResourceAccount)(nil), // 3: com.continusec.verifiabledatastructures.configuration.ResourceAccount
}
var file_configuration_proto_depIdxs = []int32{
	3, // 0: com.continusec.verifiabledatastructures.configuration.ServerConfig.accounts:type_name -> com.continusec.verifiabledatastructures.configuration.ResourceAccount
	0, // 1: com.continusec.verifiabledatastructures.configuration.AccessPolicy.permissions:type_name -> com.continusec.verifiabledatastructures.configuration.Permission
	2, // 2: com.continusec.verifiabledatastructures.configuration.ResourceAccount.policy:type_name -> com.continusec.verifiabledatastructures.configuration.AccessPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		EnumInfos:         file_configuration_proto_enumTypes,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
