// Code generated by protoc-gen-go.
// source: mutation.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Mutation struct {
	// one of the following
	LogCreate   *LogCreateRequest   `protobuf:"bytes,1,opt,name=log_create,json=logCreate" json:"log_create,omitempty"`
	MapCreate   *MapCreateRequest   `protobuf:"bytes,2,opt,name=map_create,json=mapCreate" json:"map_create,omitempty"`
	LogDelete   *LogDeleteRequest   `protobuf:"bytes,3,opt,name=log_delete,json=logDelete" json:"log_delete,omitempty"`
	MapDelete   *MapDeleteRequest   `protobuf:"bytes,4,opt,name=map_delete,json=mapDelete" json:"map_delete,omitempty"`
	LogAddEntry *LogAddEntryRequest `protobuf:"bytes,5,opt,name=log_add_entry,json=logAddEntry" json:"log_add_entry,omitempty"`
}

func (m *Mutation) Reset()                    { *m = Mutation{} }
func (m *Mutation) String() string            { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()               {}
func (*Mutation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Mutation) GetLogCreate() *LogCreateRequest {
	if m != nil {
		return m.LogCreate
	}
	return nil
}

func (m *Mutation) GetMapCreate() *MapCreateRequest {
	if m != nil {
		return m.MapCreate
	}
	return nil
}

func (m *Mutation) GetLogDelete() *LogDeleteRequest {
	if m != nil {
		return m.LogDelete
	}
	return nil
}

func (m *Mutation) GetMapDelete() *MapDeleteRequest {
	if m != nil {
		return m.MapDelete
	}
	return nil
}

func (m *Mutation) GetLogAddEntry() *LogAddEntryRequest {
	if m != nil {
		return m.LogAddEntry
	}
	return nil
}

type LeafNode struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *LeafNode) Reset()                    { *m = LeafNode{} }
func (m *LeafNode) String() string            { return proto.CompactTextString(m) }
func (*LeafNode) ProtoMessage()               {}
func (*LeafNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LeafNode) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type TreeNode struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *TreeNode) Reset()                    { *m = TreeNode{} }
func (m *TreeNode) String() string            { return proto.CompactTextString(m) }
func (*TreeNode) ProtoMessage()               {}
func (*TreeNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TreeNode) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type LogTreeHash struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *LogTreeHash) Reset()                    { *m = LogTreeHash{} }
func (m *LogTreeHash) String() string            { return proto.CompactTextString(m) }
func (*LogTreeHash) ProtoMessage()               {}
func (*LogTreeHash) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LogTreeHash) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type EntryIndex struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
}

func (m *EntryIndex) Reset()                    { *m = EntryIndex{} }
func (m *EntryIndex) String() string            { return proto.CompactTextString(m) }
func (*EntryIndex) ProtoMessage()               {}
func (*EntryIndex) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *EntryIndex) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Mutation)(nil), "continusec.verifiabledatastructures.server.store.Mutation")
	proto.RegisterType((*LeafNode)(nil), "continusec.verifiabledatastructures.server.store.LeafNode")
	proto.RegisterType((*TreeNode)(nil), "continusec.verifiabledatastructures.server.store.TreeNode")
	proto.RegisterType((*LogTreeHash)(nil), "continusec.verifiabledatastructures.server.store.LogTreeHash")
	proto.RegisterType((*EntryIndex)(nil), "continusec.verifiabledatastructures.server.store.EntryIndex")
}

func init() { proto.RegisterFile("mutation.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x69, 0xd3, 0xbe, 0xb4, 0x9b, 0x57, 0x91, 0xe0, 0x21, 0x88, 0xa0, 0xe4, 0xe4, 0x29,
	0x88, 0x9e, 0xc4, 0x93, 0xff, 0x40, 0x21, 0xf5, 0x10, 0x3c, 0x88, 0x97, 0x30, 0xc9, 0x4e, 0xd3,
	0x85, 0x24, 0x1b, 0x77, 0x27, 0x45, 0x3f, 0xa7, 0x5f, 0x48, 0x76, 0xd3, 0x45, 0x29, 0x0a, 0xe6,
	0x36, 0x79, 0x66, 0x9e, 0x5f, 0x7e, 0x90, 0xb0, 0xdd, 0xba, 0x23, 0x20, 0x21, 0x9b, 0xb8, 0x55,
	0x92, 0x64, 0x70, 0x5a, 0xc8, 0x86, 0x44, 0xd3, 0x69, 0x2c, 0xe2, 0x35, 0x2a, 0xb1, 0x14, 0x90,
	0x57, 0xc8, 0x81, 0x40, 0x93, 0xea, 0x0a, 0xea, 0x14, 0xea, 0x58, 0xa3, 0x5a, 0xa3, 0x8a, 0x35,
	0x49, 0x85, 0x07, 0x73, 0x68, 0x45, 0x5f, 0x8e, 0x3e, 0x3c, 0x36, 0x5b, 0x6c, 0x78, 0xc1, 0x33,
	0x63, 0x95, 0x2c, 0xb3, 0x42, 0x21, 0x10, 0x86, 0xa3, 0xe3, 0xd1, 0x89, 0x7f, 0x76, 0x11, 0xff,
	0x05, 0x6f, 0x80, 0x89, 0x2c, 0x6f, 0x6c, 0x33, 0xc5, 0xd7, 0x0e, 0x35, 0xa5, 0xf3, 0xca, 0x25,
	0x86, 0x5c, 0x43, 0xeb, 0xc8, 0xe3, 0x81, 0xe4, 0x05, 0xb4, 0x5b, 0xe4, 0xda, 0x25, 0xce, 0x99,
	0x63, 0x85, 0x84, 0xa1, 0x37, 0xdc, 0xf9, 0xd6, 0x36, 0xbf, 0x3b, 0xf7, 0x89, 0x73, 0xde, 0x90,
	0x27, 0xc3, 0x9d, 0xb7, 0xc8, 0xb5, 0x4b, 0x82, 0x8c, 0xed, 0x18, 0x67, 0xe0, 0x3c, 0xc3, 0x86,
	0xd4, 0x7b, 0x38, 0xb5, 0xf0, 0xcb, 0x21, 0xda, 0x57, 0x9c, 0xdf, 0x99, 0xae, 0xc3, 0xfb, 0xd5,
	0x57, 0x16, 0x1d, 0xb2, 0x59, 0x82, 0xb0, 0x7c, 0x94, 0x1c, 0x83, 0x3d, 0xe6, 0xd5, 0xb4, 0xb2,
	0x5f, 0xf3, 0x7f, 0x6a, 0x46, 0xb3, 0x7d, 0x52, 0x88, 0xbf, 0x6c, 0x8f, 0x98, 0x9f, 0xc8, 0xd2,
	0x1c, 0xdc, 0x83, 0x5e, 0xfd, 0x70, 0x10, 0x31, 0x66, 0xdf, 0xf2, 0xd0, 0x70, 0x7c, 0x0b, 0xf6,
	0xd9, 0x54, 0x98, 0xc1, 0x5e, 0x78, 0x69, 0xff, 0x70, 0x3d, 0x79, 0x19, 0xb7, 0x79, 0xfe, 0xcf,
	0xfe, 0x63, 0xe7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0xf5, 0x7c, 0x66, 0xb2, 0x02, 0x00,
	0x00,
}
