// Code generated by protoc-gen-go.
// source: mutation.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MutationType int32

const (
	MutationType_MUT_UNKNOWN     MutationType = 0
	MutationType_MUT_LOG_CREATE  MutationType = 1
	MutationType_MUT_LOG_DESTROY MutationType = 2
	MutationType_MUT_LOG_ADD     MutationType = 3
	MutationType_MUT_MAP_CREATE  MutationType = 4
	MutationType_MUT_MAP_DESTROY MutationType = 5
)

var MutationType_name = map[int32]string{
	0: "MUT_UNKNOWN",
	1: "MUT_LOG_CREATE",
	2: "MUT_LOG_DESTROY",
	3: "MUT_LOG_ADD",
	4: "MUT_MAP_CREATE",
	5: "MUT_MAP_DESTROY",
}
var MutationType_value = map[string]int32{
	"MUT_UNKNOWN":     0,
	"MUT_LOG_CREATE":  1,
	"MUT_LOG_DESTROY": 2,
	"MUT_LOG_ADD":     3,
	"MUT_MAP_CREATE":  4,
	"MUT_MAP_DESTROY": 5,
}

func (x MutationType) String() string {
	return proto.EnumName(MutationType_name, int32(x))
}
func (MutationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Mutation struct {
	Operation MutationType `protobuf:"varint,1,opt,name=operation,enum=continusec.verifiabledatastructures.server.store.MutationType" json:"operation,omitempty"`
	Account   string       `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Name      string       `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Mtl       []byte       `protobuf:"bytes,4,opt,name=mtl,proto3" json:"mtl,omitempty"`
	Value     []byte       `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Extra     []byte       `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (m *Mutation) Reset()                    { *m = Mutation{} }
func (m *Mutation) String() string            { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()               {}
func (*Mutation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Mutation) GetOperation() MutationType {
	if m != nil {
		return m.Operation
	}
	return MutationType_MUT_UNKNOWN
}

func (m *Mutation) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Mutation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mutation) GetMtl() []byte {
	if m != nil {
		return m.Mtl
	}
	return nil
}

func (m *Mutation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Mutation) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type LeafNode struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *LeafNode) Reset()                    { *m = LeafNode{} }
func (m *LeafNode) String() string            { return proto.CompactTextString(m) }
func (*LeafNode) ProtoMessage()               {}
func (*LeafNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LeafNode) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type TreeNode struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *TreeNode) Reset()                    { *m = TreeNode{} }
func (m *TreeNode) String() string            { return proto.CompactTextString(m) }
func (*TreeNode) ProtoMessage()               {}
func (*TreeNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TreeNode) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type LogTreeHash struct {
	Mth []byte `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
}

func (m *LogTreeHash) Reset()                    { *m = LogTreeHash{} }
func (m *LogTreeHash) String() string            { return proto.CompactTextString(m) }
func (*LogTreeHash) ProtoMessage()               {}
func (*LogTreeHash) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LogTreeHash) GetMth() []byte {
	if m != nil {
		return m.Mth
	}
	return nil
}

type EntryIndex struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
}

func (m *EntryIndex) Reset()                    { *m = EntryIndex{} }
func (m *EntryIndex) String() string            { return proto.CompactTextString(m) }
func (*EntryIndex) ProtoMessage()               {}
func (*EntryIndex) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *EntryIndex) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Mutation)(nil), "continusec.verifiabledatastructures.server.store.Mutation")
	proto.RegisterType((*LeafNode)(nil), "continusec.verifiabledatastructures.server.store.LeafNode")
	proto.RegisterType((*TreeNode)(nil), "continusec.verifiabledatastructures.server.store.TreeNode")
	proto.RegisterType((*LogTreeHash)(nil), "continusec.verifiabledatastructures.server.store.LogTreeHash")
	proto.RegisterType((*EntryIndex)(nil), "continusec.verifiabledatastructures.server.store.EntryIndex")
	proto.RegisterEnum("continusec.verifiabledatastructures.server.store.MutationType", MutationType_name, MutationType_value)
}

func init() { proto.RegisterFile("mutation.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x1d, 0x1b, 0x08, 0x0f, 0x02, 0x4b, 0xf5, 0xb0, 0x83, 0x89, 0x84, 0x13, 0xf1, 0xb0,
	0x18, 0xbd, 0x9b, 0xa0, 0x2c, 0x6a, 0x84, 0x61, 0xe6, 0x88, 0xd1, 0x98, 0x90, 0x32, 0x1e, 0xb2,
	0x04, 0xda, 0xa5, 0xeb, 0x08, 0x5c, 0xfd, 0x1b, 0xfd, 0x83, 0x4c, 0x0b, 0x8d, 0x1e, 0xf4, 0xe0,
	0xed, 0x7d, 0xbf, 0xf7, 0x7d, 0x5f, 0xda, 0xa6, 0xd0, 0x5c, 0x15, 0x92, 0xca, 0x94, 0x33, 0x3f,
	0x13, 0x5c, 0x72, 0x72, 0x9e, 0x70, 0x26, 0x53, 0x56, 0xe4, 0x98, 0xf8, 0x6b, 0x14, 0xe9, 0x3c,
	0xa5, 0xd3, 0x25, 0xce, 0xa8, 0xa4, 0xb9, 0x14, 0x45, 0x22, 0x0b, 0x81, 0xb9, 0x9f, 0xa3, 0x58,
	0xa3, 0xf0, 0x73, 0xc9, 0x05, 0x76, 0x3e, 0x2d, 0xa8, 0x0e, 0xf7, 0x25, 0xe4, 0x0d, 0x6a, 0x3c,
	0x43, 0xa1, 0x85, 0x67, 0xb5, 0xad, 0x6e, 0xf3, 0xe2, 0xca, 0xff, 0x6f, 0xa5, 0x6f, 0xea, 0xe2,
	0x6d, 0x86, 0xd1, 0x77, 0x21, 0xf1, 0xe0, 0x90, 0x26, 0x09, 0x2f, 0x98, 0xf4, 0x4a, 0x6d, 0xab,
	0x5b, 0x8b, 0x8c, 0x24, 0x04, 0x1c, 0x46, 0x57, 0xe8, 0xd9, 0x1a, 0xeb, 0x99, 0xb8, 0x60, 0xaf,
	0xe4, 0xd2, 0x73, 0xda, 0x56, 0xb7, 0x11, 0xa9, 0x91, 0x1c, 0x43, 0x79, 0x4d, 0x97, 0x05, 0x7a,
	0x65, 0xcd, 0x76, 0x42, 0x51, 0xdc, 0x48, 0x41, 0xbd, 0xca, 0x8e, 0x6a, 0xd1, 0x39, 0x81, 0xea,
	0x00, 0xe9, 0x3c, 0xe4, 0xb3, 0x7d, 0xd3, 0x42, 0xdf, 0x47, 0x37, 0x2d, 0xd4, 0x36, 0x16, 0x88,
	0x7f, 0x6c, 0x4f, 0xa1, 0x3e, 0xe0, 0xef, 0xca, 0x70, 0x47, 0xf3, 0xc5, 0x2f, 0x86, 0x0e, 0x40,
	0xc0, 0xa4, 0xd8, 0xde, 0xb3, 0x19, 0x6e, 0xd4, 0x01, 0x52, 0x35, 0x68, 0x87, 0x1d, 0xed, 0xc4,
	0xd9, 0x87, 0x05, 0x8d, 0x9f, 0x0f, 0x41, 0x5a, 0x50, 0x1f, 0x8e, 0xe3, 0xc9, 0x38, 0x7c, 0x08,
	0x47, 0xcf, 0xa1, 0x7b, 0x40, 0x08, 0x34, 0x15, 0x18, 0x8c, 0x6e, 0x27, 0x37, 0x51, 0xd0, 0x8b,
	0x03, 0xd7, 0x22, 0x47, 0xd0, 0x32, 0xac, 0x1f, 0x3c, 0xc5, 0xd1, 0xe8, 0xc5, 0x2d, 0x99, 0xa4,
	0x82, 0xbd, 0x7e, 0xdf, 0xb5, 0x4d, 0x72, 0xd8, 0x7b, 0x34, 0x49, 0xc7, 0x24, 0x15, 0x33, 0xc9,
	0xf2, 0xb5, 0xf3, 0x5a, 0xca, 0xa6, 0xd3, 0x8a, 0xfe, 0x1b, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x64, 0x1b, 0xec, 0x2d, 0x02, 0x00, 0x00,
}
