//
//
//Copyright 2017 Continusec Pty Ltd
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: storage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mutation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace []byte                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// one of the following
	LogAddEntry   *LogAddEntryRequest `protobuf:"bytes,2,opt,name=log_add_entry,json=logAddEntry,proto3" json:"log_add_entry,omitempty"` // we don't have map set value, as that generates a LogAddEntryRequest to the underlying mutation log
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Mutation) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Mutation) GetLogAddEntry() *LogAddEntryRequest {
	if x != nil {
		return x.LogAddEntry
	}
	return nil
}

type LeafNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mth           []byte                 `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafNode) Reset() {
	*x = LeafNode{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafNode) ProtoMessage() {}

func (x *LeafNode) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafNode.ProtoReflect.Descriptor instead.
func (*LeafNode) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *LeafNode) GetMth() []byte {
	if x != nil {
		return x.Mth
	}
	return nil
}

type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mth           []byte                 `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *TreeNode) GetMth() []byte {
	if x != nil {
		return x.Mth
	}
	return nil
}

type LogTreeHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mth           []byte                 `protobuf:"bytes,1,opt,name=mth,proto3" json:"mth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogTreeHash) Reset() {
	*x = LogTreeHash{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTreeHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTreeHash) ProtoMessage() {}

func (x *LogTreeHash) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTreeHash.ProtoReflect.Descriptor instead.
func (*LogTreeHash) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *LogTreeHash) GetMth() []byte {
	if x != nil {
		return x.Mth
	}
	return nil
}

type EntryIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryIndex) Reset() {
	*x = EntryIndex{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryIndex) ProtoMessage() {}

func (x *EntryIndex) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryIndex.ProtoReflect.Descriptor instead.
func (*EntryIndex) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *EntryIndex) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ObjectSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectSize) Reset() {
	*x = ObjectSize{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSize) ProtoMessage() {}

func (x *ObjectSize) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSize.ProtoReflect.Descriptor instead.
func (*ObjectSize) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectSize) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MapNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// for parent nodes only
	LeftNumber  int64 `protobuf:"varint,1,opt,name=left_number,json=leftNumber,proto3" json:"left_number,omitempty"`    // if zero, default
	RightNumber int64 `protobuf:"varint,2,opt,name=right_number,json=rightNumber,proto3" json:"right_number,omitempty"` // if zero, default
	// set for parents only, if corresponding entry is non-zero
	LeftHash  []byte `protobuf:"bytes,3,opt,name=left_hash,json=leftHash,proto3" json:"left_hash,omitempty"`    // set if left is non-zero
	RightHash []byte `protobuf:"bytes,4,opt,name=right_hash,json=rightHash,proto3" json:"right_hash,omitempty"` // set if right is non-zero
	// for leaf nodes only
	LeafHash      []byte `protobuf:"bytes,6,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"` // if set, both left and right num must be zero
	Path          []byte `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`                         // if set, both left and right num must be zero
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapNode) Reset() {
	*x = MapNode{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapNode) ProtoMessage() {}

func (x *MapNode) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapNode.ProtoReflect.Descriptor instead.
func (*MapNode) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *MapNode) GetLeftNumber() int64 {
	if x != nil {
		return x.LeftNumber
	}
	return 0
}

func (x *MapNode) GetRightNumber() int64 {
	if x != nil {
		return x.RightNumber
	}
	return 0
}

func (x *MapNode) GetLeftHash() []byte {
	if x != nil {
		return x.LeftHash
	}
	return nil
}

func (x *MapNode) GetRightHash() []byte {
	if x != nil {
		return x.RightHash
	}
	return nil
}

func (x *MapNode) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

func (x *MapNode) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12/com.continusec.verifiabledatastructures.storage\x1a\tapi.proto\"\x8d\x01\n" +
	"\bMutation\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\fR\tnamespace\x12c\n" +
	"\rlog_add_entry\x18\x02 \x01(\v2?.com.continusec.verifiabledatastructures.api.LogAddEntryRequestR\vlogAddEntry\"\x1c\n" +
	"\bLeafNode\x12\x10\n" +
	"\x03mth\x18\x01 \x01(\fR\x03mth\"\x1c\n" +
	"\bTreeNode\x12\x10\n" +
	"\x03mth\x18\x01 \x01(\fR\x03mth\"\x1f\n" +
	"\vLogTreeHash\x12\x10\n" +
	"\x03mth\x18\x01 \x01(\fR\x03mth\"\"\n" +
	"\n" +
	"EntryIndex\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\" \n" +
	"\n" +
	"ObjectSize\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"\xba\x01\n" +
	"\aMapNode\x12\x1f\n" +
	"\vleft_number\x18\x01 \x01(\x03R\n" +
	"leftNumber\x12!\n" +
	"\fright_number\x18\x02 \x01(\x03R\vrightNumber\x12\x1b\n" +
	"\tleft_hash\x18\x03 \x01(\fR\bleftHash\x12\x1d\n" +
	"\n" +
	"right_hash\x18\x04 \x01(\fR\trightHash\x12\x1b\n" +
	"\tleaf_hash\x18\x06 \x01(\fR\bleafHash\x12\x12\n" +
	"\x04path\x18\a \x01(\fR\x04pathB3Z1github.com/continusec/verifiabledatastructures/pbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_storage_proto_goTypes = []any{
	(*Mutation)(nil),           // 0: com.continusec.verifiabledatastructures.storage.Mutation
	(*LeafNode)(nil),           // 1: com.continusec.verifiabledatastructures.storage.LeafNode
	(*TreeNode)(nil),           // 2: com.continusec.verifiabledatastructures.storage.TreeNode
	(*LogTreeHash)(nil),        // 3: com.continusec.verifiabledatastructures.storage.LogTreeHash
	(*EntryIndex)(nil),         // 4: com.continusec.verifiabledatastructures.storage.EntryIndex
	(*ObjectSize)(nil),         // 5: com.continusec.verifiabledatastructures.storage.ObjectSize
	(*MapNode)(nil),            // 6: com.continusec.verifiabledatastructures.storage.MapNode
	(*LogAddEntryRequest)(nil), // 7: com.continusec.verifiabledatastructures.api.LogAddEntryRequest
}
var file_storage_proto_depIdxs = []int32{
	7, // 0: com.continusec.verifiabledatastructures.storage.Mutation.log_add_entry:type_name -> com.continusec.verifiabledatastructures.api.LogAddEntryRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
